// jquery開始
$(document).ready(function(){
    $('.MemberDiv').click(function(){
        $('.member').show();
        $('.OrderTracking').hide();
        $('.MyCollection').hide();
        $('.Ihaveaquestion').hide();
        $('.MemberDiv').css("background-color","#2f4f4f");
        $('.OrderTrackingDiv').css("background-color","#eeebeb");
        $('.MyCollectionDiv').css("background-color","#eeebeb");
        $('.IhaveaquestionDiv').css("background-color","#eeebeb");
        $('.MemberDiv').css("color","white");
        $('.OrderTrackingDiv').css("color","#2f4f4f");
        $('.MyCollectionDiv').css("color","#2f4f4f");
        $('.IhaveaquestionDiv').css("color","#2f4f4f");
    });
    $('.OrderTrackingDiv').click(function(){
        $('.member').hide();
        $('.OrderTracking').show();
        $('.MyCollection').hide();
        $('.Ihaveaquestion').hide();
        $('.OrderTrackingDiv').css("background-color","#2f4f4f");
        $('.MemberDiv').css("background-color","#eeebeb");
        $('.MyCollectionDiv').css("background-color","#eeebeb");
        $('.IhaveaquestionDiv').css("background-color","#eeebeb");
        $('.OrderTrackingDiv').css("color","white");
        $('.MemberDiv').css("color","#2f4f4f");
        $('.MyCollectionDiv').css("color","#2f4f4f");
        $('.IhaveaquestionDiv').css("color","#2f4f4f");
    });
    $('.MyCollectionDiv').click(function(){
        $('.member').hide();
        $('.OrderTracking').hide();
        $('.MyCollection').show();
        $('.Ihaveaquestion').hide();
        $('.MyCollectionDiv').css("background-color","#2f4f4f");
        $('.OrderTrackingDiv').css("background-color","#eeebeb");
        $('.MemberDiv').css("background-color","#eeebeb");
        $('.IhaveaquestionDiv').css("background-color","#eeebeb");
        $('.MyCollectionDiv').css("color","white");
        $('.OrderTrackingDiv').css("color","#2f4f4f");
        $('.MemberDiv').css("color","#2f4f4f");
        $('.IhaveaquestionDiv').css("color","#2f4f4f");
    });
    $('.IhaveaquestionDiv').click(function(){
        $('.member').hide();
        $('.OrderTracking').hide();
        $('.MyCollection').hide();
        $('.Ihaveaquestion').show();
        $('.IhaveaquestionDiv').css("background-color","#2f4f4f");
        $('.OrderTrackingDiv').css("background-color","#eeebeb");
        $('.MyCollectionDiv').css("background-color","#eeebeb");
        $('.MemberDiv').css("background-color","#eeebeb");
        $('.IhaveaquestionDiv').css("color","white");
        $('.OrderTrackingDiv').css("color","#2f4f4f");
        $('.MyCollectionDiv').css("color","#2f4f4f");
        $('.MemberDiv').css("color","#2f4f4f");
    });
});